# Generated by Django 3.0.4 on 2020-03-07 19:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20200307_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_identification',
            field=models.CharField(default=uuid.uuid4, max_length=20, unique=True),
        ),
    ]
